### ISSUE TITLE
Where to load services

### ISSUE THREAD

**Issue by sandeza-admin** [felipegcampos/hapi-moleculer#1]
Where should I call broker.loadService()? I don't see it is being called anywhere.

**Comment by felipegcampos** [comment]
> Where should I call broker.loadService()? I don't see it is being called anywhere.

My sincere apologies for the delay in responding to this issue. The project has been dormant for a while as I haven't been working with moleculer in recent years. However, I will try to keep the project more up-to-date from now on.

Regarding your question, in general your hapi project should be the gateway API and as such, shouldn't use `broker.call`. However, if your use case still requires you to create actions on the web server, you can provide a `ServiceBroker` instance as mentioned in https://github.com/felipegcampos/hapi-moleculer#options. So you could load the actions using this instance.
